//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VaibikParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IVaibikParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class VaibikParserBaseListener : IVaibikParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] VaibikParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] VaibikParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.topLevelItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopLevelItem([NotNull] VaibikParser.TopLevelItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.topLevelItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopLevelItem([NotNull] VaibikParser.TopLevelItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaration([NotNull] VaibikParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaration([NotNull] VaibikParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDeclaration([NotNull] VaibikParser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDeclaration([NotNull] VaibikParser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] VaibikParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] VaibikParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] VaibikParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] VaibikParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.fullType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFullType([NotNull] VaibikParser.FullTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.fullType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFullType([NotNull] VaibikParser.FullTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] VaibikParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] VaibikParser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] VaibikParser.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] VaibikParser.ArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.globalVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalVariableDeclaration([NotNull] VaibikParser.GlobalVariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.globalVariableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalVariableDeclaration([NotNull] VaibikParser.GlobalVariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] VaibikParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] VaibikParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] VaibikParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] VaibikParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementList([NotNull] VaibikParser.StatementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementList([NotNull] VaibikParser.StatementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] VaibikParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] VaibikParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] VaibikParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] VaibikParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.arrayAssignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAssignmentStatement([NotNull] VaibikParser.ArrayAssignmentStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.arrayAssignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAssignmentStatement([NotNull] VaibikParser.ArrayAssignmentStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.sideEffectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSideEffectStatement([NotNull] VaibikParser.SideEffectStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.sideEffectStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSideEffectStatement([NotNull] VaibikParser.SideEffectStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] VaibikParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] VaibikParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.loopOnlyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopOnlyStatement([NotNull] VaibikParser.LoopOnlyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.loopOnlyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopOnlyStatement([NotNull] VaibikParser.LoopOnlyStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.loopBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopBody([NotNull] VaibikParser.LoopBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.loopBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopBody([NotNull] VaibikParser.LoopBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.whileBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileBody([NotNull] VaibikParser.WhileBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.whileBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileBody([NotNull] VaibikParser.WhileBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.loopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopStatement([NotNull] VaibikParser.LoopStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.loopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopStatement([NotNull] VaibikParser.LoopStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] VaibikParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] VaibikParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.assignmentExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpr([NotNull] VaibikParser.AssignmentExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.assignmentExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpr([NotNull] VaibikParser.AssignmentExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] VaibikParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] VaibikParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] VaibikParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] VaibikParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] VaibikParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] VaibikParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.ioStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIoStatement([NotNull] VaibikParser.IoStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.ioStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIoStatement([NotNull] VaibikParser.IoStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.inputList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputList([NotNull] VaibikParser.InputListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.inputList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputList([NotNull] VaibikParser.InputListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] VaibikParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] VaibikParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] VaibikParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] VaibikParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOrExpression([NotNull] VaibikParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOrExpression([NotNull] VaibikParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndExpression([NotNull] VaibikParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndExpression([NotNull] VaibikParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpression([NotNull] VaibikParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpression([NotNull] VaibikParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] VaibikParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] VaibikParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] VaibikParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.additiveExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] VaibikParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] VaibikParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.multiplicativeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] VaibikParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryOp</c>
	/// labeled alternative in <see cref="VaibikParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryOp([NotNull] VaibikParser.UnaryOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryOp</c>
	/// labeled alternative in <see cref="VaibikParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryOp([NotNull] VaibikParser.UnaryOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>primaryAtom</c>
	/// labeled alternative in <see cref="VaibikParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryAtom([NotNull] VaibikParser.PrimaryAtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>primaryAtom</c>
	/// labeled alternative in <see cref="VaibikParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryAtom([NotNull] VaibikParser.PrimaryAtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary([NotNull] VaibikParser.PrimaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary([NotNull] VaibikParser.PrimaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAccess([NotNull] VaibikParser.ArrayAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.arrayAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAccess([NotNull] VaibikParser.ArrayAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.callSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallSuffix([NotNull] VaibikParser.CallSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.callSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallSuffix([NotNull] VaibikParser.CallSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] VaibikParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] VaibikParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.builtinFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltinFunctionCall([NotNull] VaibikParser.BuiltinFunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.builtinFunctionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltinFunctionCall([NotNull] VaibikParser.BuiltinFunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] VaibikParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] VaibikParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] VaibikParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] VaibikParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.logicalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalLiteral([NotNull] VaibikParser.LogicalLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.logicalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalLiteral([NotNull] VaibikParser.LogicalLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] VaibikParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] VaibikParser.ConstantContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
