//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VaibikParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="VaibikParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IVaibikParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] VaibikParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] VaibikParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.topLevelItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelItem([NotNull] VaibikParser.TopLevelItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.topLevelItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelItem([NotNull] VaibikParser.TopLevelItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] VaibikParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] VaibikParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.procedureDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureDeclaration([NotNull] VaibikParser.ProcedureDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.procedureDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureDeclaration([NotNull] VaibikParser.ProcedureDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] VaibikParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] VaibikParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] VaibikParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] VaibikParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.fullType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFullType([NotNull] VaibikParser.FullTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.fullType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFullType([NotNull] VaibikParser.FullTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] VaibikParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] VaibikParser.TypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayType([NotNull] VaibikParser.ArrayTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayType([NotNull] VaibikParser.ArrayTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.globalVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalVariableDeclaration([NotNull] VaibikParser.GlobalVariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.globalVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalVariableDeclaration([NotNull] VaibikParser.GlobalVariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] VaibikParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] VaibikParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] VaibikParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] VaibikParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementList([NotNull] VaibikParser.StatementListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementList([NotNull] VaibikParser.StatementListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] VaibikParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] VaibikParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] VaibikParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] VaibikParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.arrayAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAssignmentStatement([NotNull] VaibikParser.ArrayAssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.arrayAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAssignmentStatement([NotNull] VaibikParser.ArrayAssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.sideEffectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSideEffectStatement([NotNull] VaibikParser.SideEffectStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.sideEffectStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSideEffectStatement([NotNull] VaibikParser.SideEffectStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] VaibikParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] VaibikParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopStatement([NotNull] VaibikParser.LoopStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopStatement([NotNull] VaibikParser.LoopStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>whileLoop</c>
	/// labeled alternative in <see cref="VaibikParser.loopControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] VaibikParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>whileLoop</c>
	/// labeled alternative in <see cref="VaibikParser.loopControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] VaibikParser.WhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>forLoop</c>
	/// labeled alternative in <see cref="VaibikParser.loopControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoop([NotNull] VaibikParser.ForLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>forLoop</c>
	/// labeled alternative in <see cref="VaibikParser.loopControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoop([NotNull] VaibikParser.ForLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.assignmentExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpr([NotNull] VaibikParser.AssignmentExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.assignmentExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpr([NotNull] VaibikParser.AssignmentExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] VaibikParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] VaibikParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] VaibikParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] VaibikParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.ioStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIoStatement([NotNull] VaibikParser.IoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.ioStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIoStatement([NotNull] VaibikParser.IoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.inputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputList([NotNull] VaibikParser.InputListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.inputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputList([NotNull] VaibikParser.InputListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] VaibikParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] VaibikParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] VaibikParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] VaibikParser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] VaibikParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] VaibikParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] VaibikParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] VaibikParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] VaibikParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] VaibikParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] VaibikParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] VaibikParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] VaibikParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] VaibikParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] VaibikParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] VaibikParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryOp</c>
	/// labeled alternative in <see cref="VaibikParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOp([NotNull] VaibikParser.UnaryOpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryOp</c>
	/// labeled alternative in <see cref="VaibikParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOp([NotNull] VaibikParser.UnaryOpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>primaryAtom</c>
	/// labeled alternative in <see cref="VaibikParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryAtom([NotNull] VaibikParser.PrimaryAtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>primaryAtom</c>
	/// labeled alternative in <see cref="VaibikParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryAtom([NotNull] VaibikParser.PrimaryAtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] VaibikParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] VaibikParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccess([NotNull] VaibikParser.ArrayAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.arrayAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccess([NotNull] VaibikParser.ArrayAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] VaibikParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] VaibikParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.builtinFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuiltinFunctionCall([NotNull] VaibikParser.BuiltinFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.builtinFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuiltinFunctionCall([NotNull] VaibikParser.BuiltinFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] VaibikParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] VaibikParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] VaibikParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] VaibikParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.logicalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalLiteral([NotNull] VaibikParser.LogicalLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.logicalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalLiteral([NotNull] VaibikParser.LogicalLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VaibikParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] VaibikParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VaibikParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] VaibikParser.ConstantContext context);
}
